### ISSUE TITLE
error when homebridge generate certificates

### ISSUE THREAD

**Issue by lu-mueller** [arnecls/homebridge-bosch-alert-system#1]
**Describe Your Problem:**
When I try to let homebridge generate my certificates, I get an error.

**Logs:**
`error:0909006C:PEM routines:get_name:no start line`

**Plugin Config:**
```
"name": "Alert System",
"host": "192.168.178.20",
"autoPair": true,
"systemPassword": "password",
"platform": "BoschAlertHomebridgePlugin"
```

**Environment:**
* **Plugin Version**: 1.0.2
* **Homebridge Version**: 1.3.9
* **Node.js Version**: 16.13.1
* **NPM Version**: 4.8.3
* **Operating System**: Raspbian

**Comment by danielschmitz87** [comment]
Same problem for me

**Comment by lu-mueller** [comment]
That doesn't solve the problem. But I used [iobroker](https://github.com/holomekc/ioBroker.bshb/wiki/Yahka-Security-System) instead.

**Comment by dan3o3** [comment]
It seems the generated certs/keys are written to the wrong files. The key is written to bosch-client-cert.txt and the cert to bosch-client-key.txt. After renaming these files vice versa the plugin works fine for me.
